version: '3.2'

services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/bd
    ports:
      - 5432:5432  
    networks:
      - elk  
    env_file: 
      - '.env'

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elk
    env_file: 
      - '.env'  

  logstash:
    container_name: logstash
    build:
      context: logstash/
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/config/pipelines.yml
        target: /usr/share/logstash/config/pipelines.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline/db_local_test.cfg
        target: /usr/share/logstash/pipeline/db_local_test.cfg
      - type: bind
        source: ./logstash/pipeline/db_local_foobar.cfg
        target: /usr/share/logstash/pipeline/db_local_foobar.cfg
        read_only: true
      - type: bind
        source: ./logstash/config/jdbc/postgresql-42.2.18.jar
        target: /usr/share/logstash/postgresql-42.2.18.jar
        read_only: true  
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    env_file: 
      - '.env'
    networks:
      - elk 
    depends_on:
      - db
      - elasticsearch

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.10.2
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
    env_file: 
      - '.env'

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
